version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  clever-cloud-deployer:
    docker:
      - image: cimg/node:lts

jobs:
  deploy:
    executor: clever-cloud-deployer
    parameters:
      clever-app-id:
        type: string
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            git config --global user.email "dsi@zenika.com"
            git config --global user.name "Zenika"
            npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link << parameters.clever-app-id >>
            clever deploy --force

workflows:
  qc-test-deploy:
    jobs:
      - node/run:
          name: prettier
          npm-run: prettier:check
          filters:
            tags:
              only: /^v.*/
      - node/test:
          name: tests
          filters:
            tags:
              only: /^v.*/
      - deploy:
          name: deploy-staging
          requires:
            - prettier
            - tests
          clever-app-id: app_f3ae1d9d-d9ad-4ce3-a019-d18a99e5c73a
          context: clever-cloud2-zenika-dev
          filters:
            branches:
              only: upgrade_ci
      - deploy:
          name: deploy-production
          requires:
            - prettier
            - tests
          clever-app-id: app_fe53126e-88fa-4a72-9e47-366b0ffed556
          context: clever-cloud2-zenika-dev
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
